// react/src/app/components/SiteProgressStepper.tsx
import { Check } from "lucide-react";

interface ChevronStepProps {
  label: string;
  status: "completed" | "active" | "pending";
  isFirst?: boolean;
}

const ChevronStep = ({
  label,
  status,
  isFirst,
}: ChevronStepProps) => {
  const getColors = () => {
    switch (status) {
      case "active":
        return "bg-green-600 text-white";
      case "completed":
        return "bg-gray-300 text-gray-700";
      case "pending":
        return "bg-gray-200 text-gray-500";
      default:
        return "bg-gray-200 text-gray-500";
    }
  };

  const getClipPath = () => {
    if (isFirst) {
      // First item: rounded left, arrow right
      return "polygon(8px 0, calc(100% - 12px) 0, 100% 50%, calc(100% - 12px) 100%, 8px 100%, 0 100%, 0 0)";
    } else {
      // Other items: arrow left, arrow right
      return "polygon(12px 0, calc(100% - 12px) 0, 100% 50%, calc(100% - 12px) 100%, 0 100%, 12px 50%)";
    }
  };

  return (
    <div
      className={`
        relative h-11 flex items-center justify-center
        ${getColors()}
        transition-all duration-200
      `}
      style={{
        clipPath: getClipPath(),
        paddingLeft: isFirst ? "20px" : "28px",
        paddingRight: "28px",
        minWidth: "150px",
      }}
    >
      <div className="flex items-center gap-2">
        {status === "active" && (
          <Check className="w-4 h-4 flex-shrink-0" />
        )}
        {status === "completed" && (
          <span className="text-sm">•</span>
        )}
        <span className="text-sm font-medium whitespace-nowrap">
          {label}
        </span>
      </div>
    </div>
  );
};

export function SiteProgressStepper() {
  const steps = [
    { label: "CDA In Place", status: "completed" as const },
    { label: "Feasibility", status: "completed" as const },
    {
      label: "Pre-Selection Visit",
      status: "completed" as const,
    },
    { label: "Site Selected", status: "completed" as const },
    { label: "1572 Form", status: "completed" as const },
    { label: "Site Initiated", status: "active" as const },
    { label: "Site Active", status: "active" as const },
  ];

  return (
    <div className="bg-white rounded-lg shadow-sm p-8">
      <div className="mb-6">
        <h2 className="text-xl font-semibold text-gray-900 mb-1">
          Site Progression
        </h2>
        <p className="text-sm text-gray-500">
          Overview of the site's activation and onboarding
          status.
        </p>
      </div>

      <div className="flex flex-wrap items-center gap-2">
        {steps.map((step, index) => (
          <ChevronStep
            key={index}
            label={step.label}
            status={step.status}
            isFirst={index === 0}
          />
        ))}
      </div>
    </div>
  );
}

// vue-dashboard/src/components/SiteProgressStepper.vue
<script setup lang="ts">
const steps = [
  { label: 'Site Identified', status: 'completed' },
  { label: 'Initial Contact', status: 'completed' },
  { label: 'Feasibility', status: 'completed' },
  { label: 'Site Selected', status: 'current' },
  { label: 'Contracting', status: 'upcoming' },
  { label: 'Active', status: 'upcoming' },
]
</script>

<template>
  <div class="bg-white rounded-xl shadow-sm border border-slate-100 p-6">
    <h3 class="text-lg font-semibold text-slate-900 mb-6">Site Progression</h3>
    <div class="flex items-center justify-between">
      <template v-for="(step, index) in steps" :key="step.label">
        <div class="flex flex-col items-center">
          <div
            :class="[
              'w-10 h-10 rounded-full flex items-center justify-center text-sm font-semibold transition-all',
              step.status === 'completed' ? 'bg-gradient-to-br from-green-400 to-green-500 text-white shadow-lg shadow-green-200' :
              step.status === 'current' ? 'bg-gradient-to-br from-blue-500 to-blue-600 text-white shadow-lg shadow-blue-200 ring-4 ring-blue-100' :
              'bg-slate-100 text-slate-400'
            ]"
          >
            <span v-if="step.status === 'completed'">✓</span>
            <span v-else>{{ index + 1 }}</span>
          </div>
          <span
            :class="[
              'mt-2 text-xs font-medium text-center max-w-[80px]',
              step.status === 'current' ? 'text-blue-600' : 
              step.status === 'completed' ? 'text-slate-700' : 'text-slate-400'
            ]"
          >
            {{ step.label }}
          </span>
        </div>
        <div
          v-if="index < steps.length - 1"
          :class="[
            'flex-1 h-1 mx-2 rounded-full transition-all',
            step.status === 'completed' ? 'bg-gradient-to-r from-green-400 to-green-500' : 'bg-slate-200'
          ]"
        />
      </template>
    </div>
  </div>
</template>
