// vue-dashboard/src/components/MetricCard.vue
<script setup lang="ts">
defineProps<{
  label: string
  icon: string
}>()
</script>

<template>
  <div class="bg-white rounded-xl shadow-sm border border-slate-100 p-6 flex-1 min-w-[200px] transition-all duration-300 hover:shadow-md hover:border-blue-200">
    <div class="flex items-start justify-between mb-4">
      <div class="p-2.5 bg-gradient-to-br from-blue-50 to-blue-100 rounded-xl">
        <span class="text-xl">{{ icon }}</span>
      </div>
    </div>
    <div class="text-3xl font-bold text-slate-900 mb-1 tracking-tight">--</div>
    <div class="text-sm text-slate-500 font-medium">{{ label }}</div>
  </div>
</template>

// src/app/components/MetricCard.tsx
import { LucideIcon } from 'lucide-react';

interface MetricCardProps {
  icon: LucideIcon;
  label: string;
  value: string | number;
  trend?: {
    direction: 'up' | 'down';
    value: string;
  };
}

export function MetricCard({ icon: Icon, label, value, trend }: MetricCardProps) {
  return (
    <div className="bg-white rounded-lg shadow-sm p-6 flex-1 min-w-[200px]">
      <div className="flex items-start justify-between mb-4">
        <div className="p-2 bg-blue-50 rounded-lg">
          <Icon className="w-5 h-5 text-blue-600" />
        </div>
        {trend && (
          <div className={`flex items-center text-sm ${trend.direction === 'up' ? 'text-green-600' : 'text-red-600'}`}>
            <span>{trend.value}</span>
          </div>
        )}
      </div>
      <div className="text-3xl font-semibold text-gray-900 mb-1">{value}</div>
      <div className="text-sm text-gray-600">{label}</div>
    </div>
  );
}
