// vue-dashboard/src/App.vue
<script setup lang="ts">
import Card from './components/Card.vue'
import AIBarriersCard from './components/AIBarriersCard.vue'
import OngoingTrials from './components/OngoingTrials.vue'
import PendingFollowUp from './components/PendingFollowUp.vue'
import SiteProgression from './components/SiteProgression.vue'
import MetricCard from './components/MetricCard.vue'
</script>

<template>
  <div class="min-h-screen bg-gradient-to-br from-slate-50 via-slate-100 to-blue-50">
    <!-- Decorative background elements -->
    <div class="fixed inset-0 -z-10 overflow-hidden">
      <div class="absolute -top-40 -right-40 h-80 w-80 rounded-full bg-blue-200 opacity-20 blur-3xl"></div>
      <div class="absolute -bottom-40 -left-40 h-96 w-96 rounded-full bg-purple-200 opacity-20 blur-3xl"></div>
      <div class="absolute top-1/2 left-1/2 h-64 w-64 -translate-x-1/2 -translate-y-1/2 rounded-full bg-amber-200 opacity-10 blur-3xl"></div>
    </div>

    <div class="mx-auto max-w-[1440px] px-8 py-8">
      <!-- Header Section -->
      <header class="mb-8">
        <div class="flex items-start gap-4 mb-6">
          <div class="p-4 bg-gradient-to-br from-blue-500 to-blue-600 rounded-2xl shadow-lg shadow-blue-200">
            <span class="text-3xl">🏥</span>
          </div>
          <div class="flex-1">
            <h1 class="text-3xl font-bold text-slate-900 mb-2 tracking-tight">
              City General Hospital
            </h1>
            <p class="text-base text-slate-600 mb-1">
              456 Health Ave, MedCity, USA
            </p>
            <p class="text-sm text-slate-500">
              Part of: 
              <a href="#" class="text-blue-600 hover:text-blue-700 font-semibold hover:underline underline-offset-2 transition-colors">
                Dr. Lisa Ray
              </a>
            </p>
          </div>
        </div>
      </header>

      <!-- Site Progression Section -->
      <section class="mb-6">
        <SiteProgression />
      </section>

      <!-- Metrics Section -->
      <section class="mb-8">
        <div class="flex gap-4 flex-wrap">
          <MetricCard 
            icon="pulse" 
            label="Active Trials" 
            :value="12" 
            deltaText="+2" 
            deltaType="up" 
          />
          <MetricCard 
            icon="users" 
            label="Enrolled Patients" 
            :value="247" 
            deltaText="+18%" 
            deltaType="up" 
          />
          <MetricCard 
            icon="trend" 
            label="Enrollment Rate" 
            value="87%" 
            deltaText="+5%" 
            deltaType="up" 
          />
          <MetricCard 
            icon="clock" 
            label="Avg. Time to Enroll" 
            value="12 days" 
            deltaText="-3 days" 
            deltaType="down" 
          />
          <MetricCard 
            icon="alert" 
            label="Screening Failures" 
            :value="34" 
          />
        </div>
      </section>

      <!-- AI-Identified Potential Barriers -->
      <section class="mb-6">
        <AIBarriersCard />
      </section>

      <!-- Bottom Two-Column Layout -->
      <section class="grid grid-cols-1 gap-6 lg:grid-cols-2">
        <OngoingTrials />
        <PendingFollowUp />
      </section>
    </div>
  </div>
</template>

// src/app/App.tsx
import {
  Building2,
  Activity,
  Users,
  TrendingUp,
  Clock,
  AlertCircle,
} from "lucide-react";
import { MetricCard } from "./components/MetricCard";
import { SiteProgressStepper } from "./components/SiteProgressStepper";
import { AIBarriers } from "./components/AIBarriers";
import { AccountHierarchy } from "./components/AccountHierarchy";
import { OngoingTrials } from "./components/OngoingTrials";
import { PendingFollowUp } from "./components/PendingFollowUp";

export default function App() {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-[1440px] mx-auto px-8 py-8">
        {/* Header Section */}
        <div className="mb-8">
          <div className="flex items-start gap-4 mb-6">
            <div className="p-3 bg-blue-100 rounded-xl">
              <Building2 className="w-8 h-8 text-blue-600" />
            </div>
            <div className="flex-1">
              <h1 className="text-3xl font-semibold text-gray-900 mb-2">
                City General Hospital
              </h1>
              <p className="text-base text-gray-600 mb-1">
                456 Health Ave, MedCity, USA
              </p>
              <p className="text-sm text-gray-600">
                Part of:{" "}
                <a
                  href="#"
                  className="text-blue-600 hover:text-blue-700 font-medium hover:underline"
                >
                  Dr. Lisa Ray
                </a>
              </p>
            </div>
          </div>
        </div>

        {/* Site Progression Section */}
        <div className="mb-6">
          <SiteProgressStepper />
        </div>

        {/* Metrics Section */}
        <div className="mb-8">
          <div className="flex gap-4 flex-wrap">
            <MetricCard
              icon={Activity}
              label="Active Trials"
              value={12}
              trend={{ direction: "up", value: "+2" }}
            />
            <MetricCard
              icon={Users}
              label="Enrolled Patients"
              value={247}
              trend={{ direction: "up", value: "+18%" }}
            />
            <MetricCard
              icon={TrendingUp}
              label="Enrollment Rate"
              value="87%"
              trend={{ direction: "up", value: "+5%" }}
            />
            <MetricCard
              icon={Clock}
              label="Avg. Time to Enroll"
              value="12 days"
              trend={{ direction: "down", value: "-3 days" }}
            />
            <MetricCard
              icon={AlertCircle}
              label="Screening Failures"
              value={34}
            />
          </div>
        </div>

        {/* AI-Identified Potential Barriers */}
        <div className="mb-6">
          <AIBarriers />
        </div>

        {/* Bottom Two-Column Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="space-y-6">
            <OngoingTrials />
            {/* <AccountHierarchy /> */}
          </div>
          <PendingFollowUp />
        </div>
      </div>
    </div>
  );
}
